### ISSUE TITLE
buffer-browserify -> buffer

### ISSUE THREAD

**Issue by alexisvincent** [jspm/nodelibs-buffer#2]
```javascript
{
    dependencies: {
        "buffer-browserify": "^4.0.0"
    }
}
```

buffer-browserify version is set to ^4.0.0. Which doesn't exist. Perhaps you meant feross/buffer?

```javascript
{
    dependencies: {
        "buffer": "^4.0.0"
    }
}
```

**Comment by alexisvincent** [comment]
Would seem that with mapping, this will break systemjs

**Comment by guybedford** [comment]
Yes this is a mistake. A PR is welcome.

**Comment by guybedford** [comment]
I've made the change and pushed out a release.

**Comment by alexisvincent** [comment]
@guybedford I sent a PR. but then realized this might cause issues, since buffer is a core lib name
